ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

#Django admin header customiztaion

urlpatterns = [
    path('',views.home, name="home"),

    path('contact',views.contact, name="contact"),
    path('products',views.products, name="products"),
    path('single/<int:pk>/',views.single, name="single"),
    path('brochure',views.brochure, name="brochure"),
    path('searchbar',views.searchbar, name="searchbar"),
    path('checkout/<int:pk>/',views.checkout, name="checkout"), #paila single bata form submit garda checkout ma janxa
    path('complete-checkout',views.completeCheckout, name="complete-checkout"), #chcekout ko form submit huda completema janxa
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
import pymysql

# Create your models here.
class Contact(models.Model):
    name =  models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)  
    message = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return self.name

    class Meta:
       verbose_name_plural = "6. Contact" 

 

class Category(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    code = models.CharField(max_length=122, null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name  
    class Meta:
       verbose_name_plural = "2. Category"  

class Product(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    code = models.CharField(max_length=122, null=True, blank=True)
    short_description = models.TextField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    details = models.TextField(max_length=500, null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
       verbose_name_plural = "1. Product" 

class OrderItem(models.Model):

    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=200, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "7. OrderItem" 


class Setting(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    location_details = models.CharField(max_length=200, null=True, blank=True)
    fb = models.URLField(max_length=200, null=True, blank=True)
    insta = models.URLField(max_length=200, null=True, blank=True)
    yt = models.URLField(max_length=200, null=True, blank=True)
    tw = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
       verbose_name_plural = "5. Setting" 

class BannerImage(models.Model):
    image = models.ImageField(null=True, blank=True)

    class Meta:
       verbose_name_plural = "3. Banner Image" 

class Brochure(models.Model):
    image = models.FileField(null=True, blank=True)

    class Meta:
       verbose_name_plural = "4. Brochure" 

store/views.py
from typing import ContextManager
from django.shortcuts import redirect, render
from store.models import Contact, Product, Category, Setting, BannerImage, Brochure, OrderItem
from django.http.response import HttpResponse
from django.views.generic import ListView
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.
def home(request):
    category_list = Category.objects.all().order_by('-id')[:4]
    product_list = Product.objects.all().order_by('-id')
    featured_list = Product.objects.filter(is_featured = True, is_active = True)[:5]
    setting = Setting.objects.first()
    banner_image = BannerImage.objects.all()
    context = {'category_list' : category_list, 'product_list' : product_list, 'featured_list': featured_list,'setting': setting, 'banner_image': banner_image}
    return render(request, 'store/index.html', context)

def contact(request):
    
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']

        Contact.objects.create(
            name = name,
            email = email,
            phone = phone,
            message = message
        )
        return HttpResponse('')
    category_list = Category.objects.all().order_by('-id')
    setting = Setting.objects.first()
    context = {'category_list' : category_list, 'setting' : setting}
    return render(request, 'store/contact.html', context)

def products(request):
    category = request.GET.get('category')
    if category == None:
        product_list = Product.objects.all()
        category_list = Category.objects.all().order_by('-id')
        setting = Setting.objects.first()
        paginator = Paginator(product_list, 6)
        page_number = request.GET.get('page') #url ma dekni value get garni ani page_number ma rakhni
        try:
            page_obj = paginator.get_page(page_number)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

    else:
      product_list = Product.objects.filter(category__name = category) 
      category_list = Category.objects.all().order_by('-id')
      setting = Setting.objects.first()
      paginator = Paginator(product_list, 3)
      page_number = request.GET.get('page') #url ma dekni value get garni ani page_number ma rakhni
      page_obj = paginator.get_page(page_number) #tei page number lai garera pageobj ma halya
    context = {'product_list': product_list,'category_list' : category_list, 'setting': setting, 'page_obj':page_obj}
    return render(request, 'store/products.html', context)

def single(request, pk):
    single = Product.objects.get(pk=pk)
    category_list = Category.objects.all().order_by('-id')
    setting = Setting.objects.first()
    context = {'single' : single, 'category_list' : category_list, 'setting': setting}
    return render(request, 'store/single.html', context)

def brochure(request):
    pdf = Brochure.objects.first()
    context = {'pdf' : pdf}
    return render(request, 'store/pdf.html', context)

def searchbar(request):
    if 'query' in request.GET:
        query = request.GET['query']
        products = Product.objects.filter(Q(name__icontains=query) | Q(code__contains=query))
        return render(request, 'store/searchbar.html', {'products':products})

    else:
        print("No information to show")
        return render(request, 'store/searchbar.html', {})     


def checkout(request, pk):
    product = Product.objects.get(id=pk)    
    quantity = request.POST['quantity']         
    category_list = Category.objects.all().order_by('-id')
    setting = Setting.objects.first()
    
    print("request.method -------", request.method)
    # print('product!!!!!!!!!!!!!!!!!!', product_id)
    # print('product!!!!!!!!!!!!!!!!!!', request.method)
    # if request.method == 'POST':
    #     name = request.POST['name']
    #     email = request.POST.get('email')
    #     phone = request.POST['phone']
    #     address = request.POST['address']
    #     quantity = request.POST['quantity']
    #     order = OrderItem(name=name,email=email,phone=phone,address=address,quantity=quantity)
    #     order.save()
    #     messages.success(request, 'Your message has been sent.')
    context = {'category_list':category_list, 'setting': setting, 'product':product, 'quantity': quantity}
    return render(request, 'store/checkout.html', context)

def completeCheckout(request):
    # print('product!!!!!!!!!!!!!!!!!!', product_id)
    # print('product!!!!!!!!!!!!!!!!!!', request.method)
    category_list = Category.objects.all().order_by('-id')[:4]
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        quantity = request.POST['quantity']
        id = request.POST['product_id']
        product = Product.objects.get(id=id)
        order = OrderItem(name=name,email=email,phone=phone,address=address,quantity=quantity,product=product)
        order.save()
        messages.success(request, 'Your message has been sent.')
    context = {'category_list':category_list}
    return render(request, 'store/checkout.html', context)
    # return redirect('/')

store/templates/store/checkout.html
{% extends 'store/main.html' %} 
{% load static %} 
{% block content %} 
{%include 'store/topnav.html' %}
{% include 'store/navbar.html' %}
<div class="content-wrapper">
<div class="login_sec">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="{% url 'home' %}">Home</a></li>
      <li class="active">Buy</li>
    </ol>
     <h3 class="mb-3"> Product is: {{product.name}}</h3>
      <h2 class="mt-4">YOUR INFORMATION</h2>
      <div class="col-md-12 log">
      <form action="/complete-checkout" method="POST" enctype="multipart/form-data" id ="post-form" autocomplete="off">
      {% csrf_token %}
  
        <input type="hidden" name="product_id" value="{{product.id}}" />
        <div class="col-md-6">
        <h5>Full Name:</h5>
        <input type="text" name="name" id ="name"/>
        </div> 
        <div class="col-md-6">
        <h5>Email:</h5>
        <input type="email" name="email" id ="email"/>
        </div>
        <div class="col-md-6">
        <h5>Phone:</h5>
        <input type="number" name="phone" id ="phone"/>
        </div>
        <div class="col-md-6">
        <h5>Address:</h5>
        <input type="text" name="address" id ="address"/>
        </div>
        <div class="col-md-6">
        <h5>Quantity:</h5>
        <input type="number" name="quantity" id ="quantity" value= "{{quantity}}" />
        </div>
        <div class="col-md-12">
        <input type="submit" value="Submit"/>
         </div>
        <!-- <div class="text-right">
        <input type="submit" class="item_add items text-right" value="Submit">
      </div> -->
      </form>
     
    </div>
    <div class="clearfix"></div>
  </div>
  <!-- <script>
    $(document).on('submit','#post-form',function(e){
      e.preventDefault(); //stpos the page from refreshing
      e.stopImmediatePropagation();
      $.ajax({
        type:'POST',
        url:'/checkout',
        data: {
             name:$('#name').val(),
             email:$('#email').val(),
             phone:$('#phone').val(),
             address:$('#address').val(),
             quantity:$('#quantity').val(),
             csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
        },
        success:function(){
              alert("Messaged Successfully");
              $("#name").val(''); //yo 4ta chai after form submission clear the input 
              $("#email").val('');
              $("#phone").val('');
              $("#address").val('');
              $("#quantity").val('');
        },
      });
    });
  
  </script> -->
</div>
</div>

{% include 'store/footer.html' %}
{% endblock %}

store/templates/store/contact.html
{% extends 'store/main.html' %}
 {% load static %} 
 {% block content %} 
 {% include 'store/topnav.html' %} 
 {% include 'store/navbar.html' %}
<div class="contact">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="{% url 'home' %}">Home</a></li>
      <li class="active">Contact</li>
    </ol>
    <div class="contact-head">
      <h2>CONTACT</h2>
      <form enctype="multipart/form-data" id ="post-form" autocomplete="off">
        {% csrf_token %}
        <div class="col-md-6 contact-left">
          <input type="text" name="name" placeholder="Name" id ="name" required />
          <input type="text" name="email" placeholder="E-mail" id ="email" required />
          <input type="text" name="phone" placeholder="Phone" id ="phone" required />
        </div>
        <div class="col-md-6 contact-right">
          <textarea name="message" placeholder="Message" id ="message"></textarea>
          <input type="submit" value="SEND" />
        </div>
        <div class="clearfix"></div>
      </form>
    </div>
    <div class="address">
      <h3>Our Locations</h3>
      <div class="locations">
        <ul>
          <li><span></span></li>
          <li>
            <div class="address-info">
              <h4>{{setting.location}}</h4>
              <p>{{setting.location_details}},</p>
              <p>Phone: {{setting.phone}}</p>
              <p>
                Mail: <a href="mailto:info@example.com">{{setting.email}}</a>
              </p>
            </div>
          </li>
        </ul>
        
      </div>
    </div>
  </div>
</div>
<script>
  $(document).on('submit','#post-form',function(e){
    e.preventDefault(); //stpos the page from refreshing
    e.stopImmediatePropagation();
    $.ajax({
      type:'POST',
      url:'/contact',
      data: {
           name:$('#name').val(),
           email:$('#email').val(),
           phone:$('#phone').val(),
           message:$('#message').val(),
           csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
      },
      success:function(){
            alert("Messaged Successfully");
            $("#name").val(''); //yo 4ta chai after form submission clear the input 
            $("#email").val('');
            $("#phone").val('');
            $("#message").val('');
      },
    });
  });

</script>
{% include 'store/footer.html' %}
{% endblock %}

store/templates/store/content.html
{% extends 'store/main.html' %} 
{% load static %} 
{% block content %}
<!-- banner -->
<div class="content"> 
  <div class="container">
    
    <div class="slider">
         
      <ul class="rslides" id="slider1">
        {% for banner in banner_image %} 
        <li><img src="{{banner.image.url}}" alt="" /></li>
        {% endfor %} 
      </ul>  
       
    </div>
   
  </div>
 
</div>
<script>
  // You can also use "$(window).load(function() {"
  $(function () {
    // Slideshow 1
    $("#slider1").responsiveSlides({
       auto: true,
   nav: true,
   speed: 500,
   namespace: "callbacks",
    });
  });
</script>



<div class="top-sellers">
  <div class="container">
    <h3>FEATURED</h3>
   
    <div class="seller-grids">
      {% for product in featured_list %}
      <div class="col-md-2 seller-grid">
        <a href="{% url 'products' %}"><img src="{{product.image.url}}" alt="" /></a>
        <h4><a href="{% url 'products' %}">{{product.name}}</a></h4>
        <span>ID: {{product.code}}</span>
      </div>
      {% endfor %}
      <div class="clearfix"></div>
    </div>
  </div>

</div>


<div class="top-sellers">
  <div class="container">
    <h3>OUR PRODUCTS</h3>
    {% for category in category_list %}
        <div class="row">
          
              <h4 class="my-4">{{category.name}}</h4>
              {% for product in category.product_set.all %}
              <div class="col-md-4">
                
                <div class="thumbnail">
                    <img src="{{product.image.url}}" style="width:100%">
                    <div class="caption">
                      <p>{{product.short_description}}</p>
                    </div>
                
                </div>
 
                
              </div class="view">
              {% endfor %}
              <div class=" text-center">
              <a class="color1" href="{% url 'products' %}?category={{category.name}}">
                <input type="button" class="item_add items "value="View All">
              </a>
 
              </div>  
        </div>
    {% endfor %}
    
  </div>

</div>
 
{% endblock %}

store/templates/store/footer.html
{% load static %}
<div class="footer-content">
  <div class="container">
    <div class="ftr-grids">
      <div class="col-md-3 ftr-grid">
        <h4>About Us</h4>
        <ul>
          <li><a href="{% url 'home' %}">Who We Are</a></li>
          <li><a href="{% url 'contact' %}">Contact Us</a></li>
        </ul>
      </div>
      <div class="col-md-3 ftr-grid">
        <h4>Customer service</h4>
        <ul>
          <li><a href="#">FAQ</a></li>
          <li><a href="#">Shipping</a></li>
          <li><a href="#">Cancellation</a></li>
          <li><a href="#">Returns</a></li>
          <li><a href="#">Bulk Orders</a></li>
          <li><a href="#">Buying Guides</a></li>
        </ul>
      </div>
      <div class="col-md-3 ftr-grid">
        <h4>Your account</h4>
        <ul>
          <li><a href="{% url 'contact' %}">Your Account</a></li>
          <li><a href="#">Personal Information</a></li>
          <li><a href="#">Addresses</a></li>
          <li><a href="#">Discount</a></li>
          <li><a href="#">Track your order</a></li>
        </ul>
      </div>
      <div class="col-md-3 ftr-grid">
        <h4>Categories</h4>
        
        <ul>
          {% for category in category_list %}
          <li><a href="{% url 'products' %}?category={{category.name}}">> {{category.name}}</a></li>
          {% endfor %}
        </ul>
        
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<div class="footer">
  <div class="container">
    <div class="copywrite">
      <p>
        Copyright © 2022 Furnyish Store All rights reserved | Design by
        <a href="http://w3layouts.com">Index Innovate</a>
      </p>
    </div>
  </div>
</div>

store/templates/store/index.html
{% extends 'store/main.html' %} 
{% load static %} 
{% block content %}

{% include 'store/topnav.html' %}
{% include 'store/navbar.html' %}
{% include 'store/content.html' %}
{% include 'store/footer.html' %}
{% endblock %}

store/templates/store/login.html
hello

store/templates/store/main.html
<!DOCTYPE HTML>
{% load static %}
<html>
<head>
<title>Furnyish Store a Ecommerce Category Flat Bootstarp Responsive Website Template | Home :: w3layouts</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link href="{% static 'store/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary JavaScript plugins) -->
<script type='text/javascript' src="{% static 'store/js/jquery-1.11.1.min.js' %}"></script>
<!-- Custom Theme files -->
<link href="{% static 'store/css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Furnyish Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Montserrat|Raleway:400,200,300,500,600,700,800,900,100' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Aladin' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">
<!-- start menu -->
<link href="{% static 'store/css/megamenu.css' %}" rel="stylesheet" type="text/css" media="all" />

<script type="text/javascript" src="{% static 'store/js/megamenu.js' %}"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
<script src="{% static 'store/js/menu_jquery.js' %}"></script>
<script src="{% static 'store/js/simpleCart.min.js' %}"> </script>
<script src="{% static 'store/js/responsiveslides.min.js' %}"></script>
  
</head>
<body>
  <!-- {% for message in messages %}
  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong>Message: </strong>{{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %} -->

    {% block content %}




    <script>
      // You can also use "$(window).load(function() {"
      $(function () {
        // Slideshow 1
        $("#slider1").responsiveSlides({
           auto: true,
       nav: true,
       speed: 500,
       namespace: "callbacks",
        });
      });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% endblock %}

</body>
</html>

store/templates/store/navbar.html
{% load static %}
<!-- navbar -->
<div class="header_top">
  <div class="container">
    <div class="logo">
      <a href="{% url 'home' %}"><img src="{% static 'store/images/logo.png' %}" alt="" /></a>
    </div>
    <div class="header_right">	
      <!-- <div class="login"> -->
        <a href="{% url 'brochure' %}" target="_blank" >Brochure</a>
      <!-- </div>				  -->
    </div>
  </div>
</div>
<!-- cart -->

<div class="mega_nav">
  <div class="container">
    <div class="menu_sec">
      <!-- start header menu -->
      <ul class="megamenu skyblue">
        <li class=" active grid">
          <a class="color1" href="{% url 'home' %}">Home</a>
        </li>
        
        <li class="grid">
          {% for category in category_list %}
          <a class="color1" href="{% url 'products' %}?category={{category.name}}">{{category.name}}</a>
          {% endfor %}
        </li>
       
      </ul>

      <div class="search">
        <form action="{% url 'searchbar' %}" method="GET">
          <input type="text" value="{{request.GET.query}}" name="query" placeholder="Search..." />
          <input type="submit" value=""/>
        </form>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

store/templates/store/pdf.html
{% load static %}

<iframe src="{{pdf.image.url}}" type="application/pdf" width="100%" height="100%">
</iframe>

store/templates/store/products.html
{% extends 'store/main.html' %} 
{% load static %} 
{% block content %} 
{% include 'store/topnav.html' %} 
{% include 'store/navbar.html' %}

<div class="login_sec">
    <div class="container">
        <ol class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li class="active">Products</li>
        </ol>
        <h2>Products</h2>
        
        <div class="col-md-12 product-model-sec">
            {% for product in page_obj.object_list %} 
                <a href="{% url 'single' product.id %}">
                    <div class="product-grid love-grid">
                        <div class="more-product"><span> </span></div>						
                            <div class="product-img b-link-stripe b-animate-go  thickbox">
                                <img src="{{product.image.url}}" class="img-responsive" alt=""/>
                                <div class="b-wrapper">
                                <h4 class="b-animate b-from-left  b-delay03">							
                                <button class="btns"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>Quick View</button>
                                </h4>
                                </div>
                           </div>
                    
                </a>
                    
                            <div class="product-info simpleCart_shelfItem">
                                <div class="product-info-cust prt_name">
                                    <h4>{{product.name}}</h4>
                                    <p>ID: {{product.code}}</p>							
                                </div>													
                                <div class="clearfix"> </div>
                            </div>
                    </div>
            {% endfor %} 
        </div> 
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-end">
            <li class="page-item">
              {%if page_obj.has_previous %} 
              <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
              {% endif %}
            </li>
            <li class="page-item"><a class="page-link">{{page_obj.number}}</a></li>
            <li class="page-item">
              {%if page_obj.has_next %}
              <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
              {% endif %}
            </li>
          </ul>
        </nav>
        <!-- <center>
          {%if page_obj.has_previous %} 
              <a href="?page={{page_obj.previous_page_number}}">Previous</a> 
          {% endif %}
          <span>{{page_obj.number}}</span> 
          
          {%if page_obj.has_next %}
              <a href="?page={{page_obj.next_page_number}}">Next</a>
          {% endif %}
      </center> -->


            
    </div>
    




{% include 'store/footer.html' %} {% endblock %}

store/templates/store/searchbar.html
{% extends 'store/main.html' %} 
{% load static %} 
{% block content %}
{% include 'store/topnav.html' %} 
{% include 'store/navbar.html' %}
<h2 class="text-center">Search Results</h2>
<hr>


<div class="container">
    
     <div class="top-sellers">
        <div class="container">
        {% if products.exists %}        
          <div class="seller-grids">
            {% for product in featured_list %}
            <div class="col-md-3 seller-grid">
              <a href="{% url 'products' %}"><img src="{{product.image.url}}" alt="" /></a>
              <h4><a href="{% url 'products' %}">{{product.name}}</a></h4>
              <span>ID: {{product.code}}</span>
            </div>
            {% endfor %}
            <div class="clearfix"></div>
          </div>
          {% else %}
          <p>No Products available</p>
        {% endif %} 
        </div>
      </div>
    

    
      <div class="top-sellers">
        <div class="container">
        {% if products.exists %} 
          {% for product in products %}
              <div class="row">
                
                    <h4 class="mb-4">{{product.name}}</h4>
                    <div class="col-md-4">
                      
                      <div class="thumbnail">
                          <img src="{{product.image.url}}" style="width:100%">
                          <div class="caption">
                            <p>{{product.short_description}}</p>
                          </div>
                      
                      </div>
                      
                    </div>   
              </div>
          {% endfor %}
          
        {% endif %}
        </div>
      </div>
    
</div>
{% endblock %}

store/templates/store/single.html
{% extends 'store/main.html' %} {% load static %} 
{% block content %}
{% include 'store/topnav.html' %} 
{% include 'store/navbar.html' %}

<div class="single-sec">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="{% url 'home' %}">Home</a></li>
      <li class="active">Products</li>
    </ol>
    <!-- start content -->
    <div class="col-md-9 det">    
      <div class="single_left">
        <div class="grid images_3_of_2">
            <ul id="etalage">
               <li class="list-unstyled">
                    <img src="{{single.image.url}}" alt="" class="img-thumbnail">
                   </a>
               </li>

            </ul>
            <div class="clearfix"></div>		
         </div>
     </div>
      <div class="single-right">
        <h3>{{single.short_description}}</h3>
        <div class="id"><h4>ID: {{single.code}}</h4></div>

        <div class="single-bottom1">
          <h6>Details</h6>
          <p class="prod-desc">{{single.details}}</p>
        <form method = "POST" action="{% url 'checkout' single.id  %}">
          {% csrf_token %}
          <input type="number" name="quantity">
          <div>
          <input type="submit" class="item_add items  "value="Buy Now">
          <!-- <button type="submit"> buy now </button> -->
        </div>
        </form>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="sofaset-info">
        <h4>Product Summary
        </h4>
        <p>{{single.description}}</p>
      </div>   
    </div>
  </div>
  <div class="clearfix"></div>
</div>
				   <!---->
                   <script type="text/javascript" src="{% static 'store/js/jquery-ui.min.js' %}"></script>
                   <link rel="stylesheet" type="text/css" href="{% static 'store/css/jquery-ui.css' %}">
                  <script type='text/javascript'>//<![CDATA[ 
                  $(window).load(function(){
                   $( "#slider-range" ).slider({
                              range: true,
                              min: 0,
                              max: 400000,
                              values: [ 2500, 350000 ],
                              slide: function( event, ui ) {  $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
                              }
                   });
                  $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) + " - $" + $( "#slider-range" ).slider( "values", 1 ) );

                  });//]]>  

                  </script>

{% include 'store/footer.html' %} {% endblock %}